name: Setup build artifacts
on:
  workflow_call:
    inputs:
      byond_versions:
        required: true
        type: string

jobs:
  run:
    uses: ./.github/workflows/setup_build_artifact.yml

    strategy:
      fail-fast: false
      matrix:
        setup: ${{ fromJSON(inputs.byond_versions) }}

    with:
      major: ${{ matrix.setup.major }}
      minor: ${{ matrix.setup.minor }}
